version: '3'

services:
  db:
    image: postgres
    volumes: 
      - ./postgres:/var/lib/postgresql/data
    env_file: 
      - vars.env
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: 
      - vars.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    env_file:
      - vars.env
    depends_on:
      - db
    